config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    omniauth: 'users/omniauth',
    unlocks: 'users/unlocks'
  }
  devise_scope :user do
    delete 'sign_out', :to => 'users/sessions#destroy'
    get '/login' => 'users/sessions#new'
    get '/register' => 'users/registrations#new'
    get '/settings' => 'users/registrations#edit'
    root 'users/sessions#new'
  end

  namespace :admin, path: '/master' do
    resources :teams do
      resources :team_officials
      resources :team_players
    end

    resources :pages, only: :index

    # sort by state
    get 't/:sort' => 'pages#state', as: 'state_index'
    get 't/:sort/team_players' => 'pages#team_player', as: 'team_player_state_index'
    get 't/:sort/team_officials' => 'pages#team_official', as: 'team_official_state_index'
  end

  namespace :staff, path: '/submaster' do
    resources :teams, only: [:index, :show] do
      resources :team_officials, only: [:index, :show]
      resources :team_players, only: [:index, :show]
    end
    resources :zones do
      resources :groups do
        resources :group_teams
        resources :team_schedules do
          collection do
            get :selection
          end
          resources :match_reports, except: :index
        end
      end
    end
  end

  namespace :lo, path: '/sub2master' do
    resources :teams, only: [:index, :show] do
      resources :team_officials, only: [:index, :show]
      resources :team_players, only: [:index, :show]
    end
  end

  get "/dashboard" => 'dashboards#index'
  resource :team, only: [:new, :create, :show] do
    resources :team_officials, only: [:index, :new, :create, :show, :edit, :update]
    # choose either one
    # activate new registration player
    # resources :team_players, only: [:index, :new, :create, :show, :edit, :update] do
    # de-activate new and edit player
    # resources :team_players, only: [:index, :show], except: [:new, :create, :edit, :update]
    # activate edit player only
    resources :team_players, only: [:index, :show, :edit, :update, :new, :create] do
      member do
        patch :mark_reject
      end
    end
    get 'cs/change_players' => 'team_players#change_players'
  end
  resource :team_config, only: [:show, :new, :create]
  resource :state_config, only: [:show, :new, :create]
  resources :state_managers
  resources :team_managers, except: [:show]
  resource :profile, only: [:edit, :update]
  resource :system_preference, only: [:edit, :update]

  get "/p/table_standing" => 'pages#table_standing'
  get "/p/match_schedule" => 'pages#match_schedule'
  get "/p/search" => 'pages#search', as: :search
end

app/views/admin/pages/index.html.erb
<section role="main" class="content-body">
	<header class="page-header">
		<h2>Lihat Pasukan melalui Negeri</h2>

		<div class="right-wrapper pull-right">
			<ol class="breadcrumbs">
				<li>
					<%= link_to root_path do %>
						<i class="fa fa-home"></i>
					<% end %>
				</li>
				<li><span>Lihat Pasukan melalui Negeri</span></li>
			</ol>

			<a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
		</div>
	</header>

  <div class="row">
		<div class="col-lg-12">
			<section class="panel">
				<header class="panel-heading">
					<div class="panel-actions">
						<a href="#" class="panel-action panel-action-toggle" data-panel-toggle></a>
						<a href="#" class="panel-action panel-action-dismiss" data-panel-dismiss></a>
					</div>

					<h2 class="panel-title">Lihat Pasukan melalui Negeri</h2>
				</header>
				<div class="panel-body">
          <ul class="list-inline">
            <% State.all.each do |s| %>
            <li><%= link_to s.name, admin_state_index_path(sort: s.id) %></li>
            <% end %>
          </ul>
        </div>
        <div class="panel-footer">

        </div>
      </section>
    </div>
  </div>
</section>

app/views/admin/pages/state.html.erb
<section role="main" class="content-body">
  <header class="page-header">
    <h2>Senarai Pasukan</h2>
    <div class="right-wrapper pull-right">
      <ol class="breadcrumbs">
        <li>
          <%= link_to root_path do %>
            <i class="fa fa-home"></i>
          <% end %>
        </li>
        <li>
          <span>Senarai Pasukan</span>
        </li>
      </ol>
      <a class="sidebar-right-toggle" data-open="sidebar-right">
        <i class="fa fa-chevron-left"></i>
      </a>
    </div>
  </header>
  <div class="row">
    <div class="col-md-12">
      <section class="panel">
        <header class="panel-heading">
          <h2 class="panel-title">Senarai Pasukan bagi Negeri <%= @state.name %></h2>
        </header>
        <div class="panel-body">
          <!-- Main Content Start -->
          <table class="table table-bordered table-striped mb-none" id="datatable-lbr">
            <thead>
              <tr>
                <th class="col-md-1">Bil</th>
                <th class="col-md-4">Nama Pasukan</th>
                <th class="col-md-2">ID Pasukan</th>
                <th class="col-md-2">Jumlah Pemain</th>
                <th class="col-md-2">Jumlah Pegawai</th>
              </tr>
            </thead>
            <tbody>
              <% @teams.each_with_index do |team,index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= team.team_name.upcase %></td>
                <td><%= team.team_ref_id %></td>
                <td><%= TeamPlayer.where(team: team).count %></td>
                <td><%= TeamOfficial.where(team: team).count %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <!-- Main Content End -->
        </div>
        <div class="panel-footer">
          <%= link_to "Senarai Semua Pemain", admin_team_player_state_index_path, class: "btn btn-primary" %>
          <%= link_to "Senarai Semua Pegawai", admin_team_official_state_index_path, class: "btn btn-default" %>
          <%= link_to "Kembali", admin_pages_path, class: "btn btn-default pull-right" %>
        </div>
      </section>
    </div>
  </div>
</section>

app/views/admin/pages/team_official.html.erb
<section role="main" class="content-body">
  <header class="page-header">
    <h2>Senarai Pegawai Pasukan</h2>
    <div class="right-wrapper pull-right">
      <ol class="breadcrumbs">
        <li>
          <%= link_to root_path do %>
            <i class="fa fa-home"></i>
          <% end %>
        </li>
        <li>
          <span>Senarai Pegawai Pasukan</span>
        </li>
      </ol>
      <a class="sidebar-right-toggle" data-open="sidebar-right">
        <i class="fa fa-chevron-left"></i>
      </a>
    </div>
  </header>
  <div class="row">
    <div class="col-md-12">
      <section class="panel">
        <header class="panel-heading">
          <h2 class="panel-title">Senarai Pegawai Pasukan bagi Negeri <%= @state.name %></h2>
        </header>
        <div class="panel-body">
          <!-- Main Content Start -->
          <table class="table table-bordered table-striped mb-none" id="datatable-lbr">
            <thead>
              <tr>
                <th class="col-md-1">Bil</th>
                <th class="col-md-2">Pasukan</th>
                <th>Nama</th>
                <th class="col-md-2">ID</th>
                <th class="col-md-2">Posisi</th>
              </tr>
            </thead>
            <tbody>
              <% @team_officials.each_with_index do |to, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= to.team.team_name %></td>
                <td>
                  <% if to.try(:profile_picture?) %>
                    <%= image_tag(to.profile_picture_url(:standar), class: 'img-circle', height: 15) %>
                  <% else %>
                    <%= image_tag "default-avatar.png", class: 'img-circle', height: 15 %>
                  <% end %>
                  <%= to.name.upcase %>
                </td>
                <td><%= to.ref_id %></td>
                <td><%= to.position.upcase %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <!-- Main Content End -->
        </div>
        <div class="panel-footer">
          <%= link_to "Kembali ke Data Pasukan", admin_state_index_path, class: "btn btn-default" %>
          <%= link_to "Muat Turun dalam PDF", admin_team_official_state_index_path(@state, :format => "pdf"), :class => "btn btn-success", :target => "_blank" %>
        </div>
      </section>
    </div>
  </div>
</section>

app/views/admin/pages/team_player.html.erb
<section role="main" class="content-body">
  <header class="page-header">
    <h2>Senarai Pemain Pasukan</h2>
    <div class="right-wrapper pull-right">
      <ol class="breadcrumbs">
        <li>
          <%= link_to root_path do %>
            <i class="fa fa-home"></i>
          <% end %>
        </li>
        <li>
          <span>Senarai Pemain Pasukan</span>
        </li>
      </ol>
      <a class="sidebar-right-toggle" data-open="sidebar-right">
        <i class="fa fa-chevron-left"></i>
      </a>
    </div>
  </header>
  <div class="row">
    <div class="col-md-12">
      <section class="panel">
        <header class="panel-heading">
          <h2 class="panel-title">Senarai Pemain Pasukan bagi Negeri <%= @state.name %></h2>
        </header>
        <div class="panel-body">
          <!-- Main Content Start -->
          <table class="table table-bordered table-striped mb-none" id="datatable-lbr">
            <thead>
              <tr>
                <th class="col-md-1">Bil</th>
                <th class="col-md-2">Pasukan</th>
                <th>Nama</th>
                <th class="col-md-2">Posisi</th>
                <th class="col-md-1">No Jersi</th>
                <th class="col-md-1">Umur</th>
              </tr>
            </thead>
            <tbody>
              <% @team_players.each_with_index do |tp, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= tp.team.team_name %></td>
                <td>
                  <% if tp.try(:player_picture?) %>
                    <%= image_tag(tp.player_picture_url(:standar), class: 'img-circle', height: 15) %>
                  <% else %>
                    <%= image_tag "default-avatar.png", class: 'img-circle', height: 15 %>
                  <% end %>
                  <%= tp.player_name.upcase %>
                </td>
                <td><%= tp.position.upcase %></td>
                <td><%= tp.jersey_no %></td>
                <td><%= tp.age %> tahun</td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <!-- Main Content End -->
        </div>
        <div class="panel-footer">
          <%= link_to "Kembali ke Senarai Pasukan", admin_state_index_path, class: "btn btn-default" %>
          <%= link_to "Muat Turun dalam PDF", admin_team_player_state_index_path(@state, :format => "pdf"), :class => "btn btn-success", :target => "_blank" %>
        </div>
      </section>
    </div>
  </div>
</section>