config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    omniauth: 'users/omniauth',
    unlocks: 'users/unlocks'
  }
  devise_scope :user do
    delete 'sign_out', :to => 'users/sessions#destroy'
    get '/login' => 'users/sessions#new'
    get '/register' => 'users/registrations#new'
    get '/settings' => 'users/registrations#edit'
    root 'users/sessions#new'
  end

  namespace :admin, path: '/master' do
    resources :teams do
      resources :team_officials
      resources :team_players
    end

    resources :pages, only: :index

    # sort by state
    get 't/:sort' => 'pages#state', as: 'state_index'
    get 't/:sort/team_players' => 'pages#team_player', as: 'team_player_state_index'
    get 't/:sort/team_officials' => 'pages#team_official', as: 'team_official_state_index'
  end

  namespace :staff, path: '/submaster' do
    resources :teams, only: [:index, :show] do
      resources :team_officials, only: [:index, :show]
      resources :team_players, only: [:index, :show]
    end
    resources :zones do
      resources :groups do
        resources :group_teams
        resources :team_schedules do
          collection do
            get :selection
          end
          resources :match_reports, except: :index
        end
      end
    end
  end

  namespace :lo, path: '/sub2master' do
    resources :teams, only: [:index, :show] do
      resources :team_officials, only: [:index, :show]
      resources :team_players, only: [:index, :show]
    end
  end

  get "/dashboard" => 'dashboards#index'
  resource :team, only: [:new, :create, :show] do
    resources :team_officials, only: [:index, :new, :create, :show, :edit, :update]
    # choose either one
    # activate new registration player
    # resources :team_players, only: [:index, :new, :create, :show, :edit, :update] do
    # de-activate new and edit player
    # resources :team_players, only: [:index, :show], except: [:new, :create, :edit, :update]
    # activate edit player only
    resources :team_players, only: [:index, :show, :edit, :update, :new, :create] do
      member do
        patch :mark_reject
      end
    end
    get 'cs/change_players' => 'team_players#change_players'
  end
  resource :team_config, only: [:show, :new, :create]
  resource :state_config, only: [:show, :new, :create]
  resources :state_managers
  resources :team_managers, except: [:show]
  resource :profile, only: [:edit, :update]
  resource :system_preference, only: [:edit, :update]

  get "/p/table_standing" => 'pages#table_standing'
  get "/p/match_schedule" => 'pages#match_schedule'
  get "/p/search" => 'pages#search', as: :search
end

app/models/staff.rb
module Staff
  def self.table_name_prefix
    'staff_'
  end
end

app/models/staff/game_statistic.rb
class Staff::GameStatistic < ActiveRecord::Base
  belongs_to :kod
  belongs_to :staff_match_report, :class_name => "Staff::MatchReport"
  belongs_to :team_player
end

app/models/staff/group.rb
class Staff::Group < ActiveRecord::Base
  belongs_to :staff_zone, class_name: 'Staff::Zone'
  has_many :staff_team_schedules, class_name: 'Staff::TeamSchedule'

  default_scope -> { order('staff_groups.created_at ASC') }
end

app/models/staff/zone.rb
class Staff::Zone < ActiveRecord::Base
  has_many :staff_groups, class_name: 'Staff::Group'
end

app/controllers/staff/group_teams_controller.rb
class Staff::GroupTeamsController < StaffController
  def index
    @group = Staff::Group.find params[:group_id]
    @staff_group_teams = Staff::GroupTeam.where(staff_group_id: @group)
  end

  def new
    @group = Staff::Group.find params[:group_id]
    @staff_group_team ||= Staff::GroupTeam.new
    render
  end

  def create
    @group = Staff::Group.find params[:group_id]
    @staff_group_team = Staff::GroupTeam.new team_staff_group_params
    if @staff_group_team.save
      @staff_group_team.update_attribute(:staff_group_id, @group.id)
      redirect_to staff_zone_group_group_teams_path, notice: "Kumpulan berjaya diwujudkan."
    else
      render 'new'
    end
  end

  def edit
    #code
  end

  def update
    #code
  end

  private

    def team_staff_group_params
      params.require(:staff_group_team).permit(:team_id, :staff_group_id)
    end
end

app/controllers/staff/groups_controller.rb
class Staff::GroupsController < StaffController
  def index
    @zone = Staff::Zone.find params[:zone_id]
    @staff_groups = Staff::Group.where(staff_zone_id: @zone)
  end

  def new
    @zone = Staff::Zone.find params[:zone_id]
    @staff_group ||= Staff::Group.new
    render
  end

  def create
    @zone = Staff::Zone.find params[:zone_id]
    @staff_group = Staff::Group.new team_staff_group_params
    if @staff_group.save
      @staff_group.update_attribute(:staff_zone_id, @zone.id)
      redirect_to staff_zone_groups_path, notice: "Kumpulan berjaya diwujudkan."
    else
      render 'new'
    end
  end

  private

    def team_staff_group_params
      params.require(:staff_group).permit(:name, :staff_zone_id)
    end
end

app/controllers/staff/match_reports_controller.rb
class Staff::MatchReportsController < StaffController
  def show
    @group = Staff::Group.find params[:group_id]
    @staff_team_schedule = Staff::TeamSchedule.find params[:team_schedule_id]
    @staff_match_report = Staff::MatchReport.find params[:id]
  end

  def new
    @staff_team_schedule = Staff::TeamSchedule.find params[:team_schedule_id]

    @home_team_players = TeamPlayer.where(team_id: @staff_team_schedule.home_team_id)
    @away_team_players = TeamPlayer.where(team_id: @staff_team_schedule.away_team_id)
    @players = @home_team_players + @away_team_players

    @staff_match_report = Staff::MatchReport.new
    @staff_match_report.staff_game_statistics.build
    render
  end

  def create
    @staff_team_schedule = Staff::TeamSchedule.find params[:team_schedule_id]
    @staff_match_report = Staff::MatchReport.new staff_match_report_params
    if @staff_match_report.save
      @staff_match_report.update_attributes(staff_team_schedule_id: @staff_team_schedule.id)

      @siapa1 = Staff::GroupTeam.find_by_team_id (@staff_team_schedule.home_team_id)
      @siapa2 = Staff::GroupTeam.find_by_team_id (@staff_team_schedule.away_team_id)

        current_home_gm = @siapa1.gol_masuk
        current_home_gb = @siapa1.gol_bolos
        current_away_gm = @siapa2.gol_masuk
        current_away_gb = @siapa2.gol_bolos
        perlawanan_home = @siapa1.perlawanan
        perlawanan_away = @siapa2.perlawanan
        menang_home = @siapa1.menang
        menang_away = @siapa2.menang
        kalah_home = @siapa1.kalah
        kalah_away = @siapa2.kalah
        seri_home = @siapa1.seri
        seri_away = @siapa2.seri
        mata_home = @siapa1.mata
        mata_away = @siapa2.mata

        rm = @staff_match_report
        sm = rm.staff_team_schedule.home_team_id = @siapa1.team_id
        tm = Staff::MatchReport.joins(:staff_team_schedule).where("home_team_id = ?", sm)
        gm = tm.last.score_home_team

        rb = @staff_match_report
        sb = rb.staff_team_schedule.home_team_id = @siapa1.team_id
        tb = Staff::MatchReport.joins(:staff_team_schedule).where("home_team_id = ?", sb)
        gb = tb.last.score_away_team

        @siapa1.update(gol_masuk: current_home_gm += gm)
        @siapa1.update(gol_bolos: current_home_gb += gb)
        @siapa2.update(gol_masuk: current_away_gm += gb)
        @siapa2.update(gol_bolos: current_away_gb += gm)
        @siapa1.update(perlawanan: perlawanan_home += 1)
        @siapa2.update(perlawanan: perlawanan_away += 1)

        if gm > gb
          @siapa1.update(menang: menang_home += 1)
          @siapa1.update(mata: mata_home += 3)
          @siapa2.update(kalah: kalah_away += 1)
          @siapa2.update(mata: mata_away += 0)
        elsif gm < gb
          @siapa1.update(kalah: kalah_home += 1)
          @siapa1.update(mata: mata_home += 0)
          @siapa2.update(menang: menang_away += 1)
          @siapa2.update(mata: mata_away += 3)
        elsif gm == gb
          @siapa1.update(seri: seri_home += 1)
          @siapa2.update(seri: seri_away += 1)
          @siapa1.update(mata: mata_home += 1)
          @siapa2.update(mata: mata_away += 1)
        end

      redirect_to staff_zone_group_team_schedule_match_report_path(id:@staff_match_report), notice: "Disimpan."
    else
      render 'new'
    end
  end

  def edit
    @group = Staff::Group.find params[:group_id]
    @staff_team_schedule = Staff::TeamSchedule.find params[:team_schedule_id]
    @staff_match_report = Staff::MatchReport.find params[:id]
    if @staff_match_report
      render
    else
      redirect_to staff_zone_group_team_schedule_match_report_path(id:@staff_match_report), notice: "Maaf! Keputusan perlawanan tidak dijumpai!"
    end
  end

  def update
    @group = Staff::Group.find params[:group_id]
    @staff_team_schedule = Staff::TeamSchedule.find params[:team_schedule_id]
    @staff_match_report = Staff::MatchReport.find params[:id]
    ###############################################

    @siapa1 = Staff::GroupTeam.find_by_team_id (@staff_team_schedule.home_team_id)
    @siapa2 = Staff::GroupTeam.find_by_team_id (@staff_team_schedule.away_team_id)

      current_home_gm = @siapa1.gol_masuk
      current_home_gb = @siapa1.gol_bolos
      current_away_gm = @siapa2.gol_masuk
      current_away_gb = @siapa2.gol_bolos
      menang_home = @siapa1.menang
      menang_away = @siapa2.menang
      kalah_home = @siapa1.kalah
      kalah_away = @siapa2.kalah
      seri_home = @siapa1.seri
      seri_away = @siapa2.seri
      mata_home = @siapa1.mata
      mata_away = @siapa2.mata

      rm = @staff_match_report
      sm = rm.staff_team_schedule.home_team_id = @siapa1.team_id
      tm = Staff::MatchReport.joins(:staff_team_schedule).where("home_team_id = ?", sm)
      gm = tm.last.score_home_team

      rb = @staff_match_report
      sb = rb.staff_team_schedule.home_team_id = @siapa1.team_id
      tb = Staff::MatchReport.joins(:staff_team_schedule).where("home_team_id = ?", sb)
      gb = tb.last.score_away_team

      # keputusan asal home = 2
      # edit keputusan home = 3
      # current_home_gm = 3
      # current_home_gb = 2

      # keputusan asal away = 3
      # edit keputusan away = 4
      # current_away_gm = 3
      # current_away_gb = 2

      # 3 > 2 home
      if staff_match_report_params[:score_home_team].to_i > @staff_match_report.score_home_team_was
        scgm = staff_match_report_params[:score_home_team].to_i - @staff_match_report.score_home_team_was

        @siapa1.update(gol_masuk: current_home_gm += scgm)
        @siapa2.update(gol_bolos: current_away_gb += scgm)
      end
      # 3 < 2 home
      if staff_match_report_params[:score_home_team].to_i < @staff_match_report.score_home_team_was
        scgm = @staff_match_report.score_home_team_was - staff_match_report_params[:score_home_team].to_i

        @siapa1.update(gol_masuk: current_home_gm -= scgm)
        @siapa2.update(gol_bolos: current_away_gb -= scgm)
      end

      if staff_match_report_params[:score_away_team].to_i > @staff_match_report.score_away_team_was
        scgm = staff_match_report_params[:score_away_team].to_i - @staff_match_report.score_away_team_was

        @siapa2.update(gol_masuk: current_away_gm += scgm)
        @siapa1.update(gol_bolos: current_home_gb += scgm)
      end
      # 3 < 2 home
      if staff_match_report_params[:score_away_team].to_i < @staff_match_report.score_away_team_was
        scgm = @staff_match_report.score_away_team_was - staff_match_report_params[:score_away_team].to_i

        @siapa2.update(gol_masuk: current_away_gm -= scgm)
        @siapa1.update(gol_bolos: current_home_gb -= scgm)
      end
      # reset
      if @staff_match_report.score_home_team_was > @staff_match_report.score_away_team_was
        if staff_match_report_params[:score_home_team].to_i < staff_match_report_params[:score_away_team].to_i
          @siapa1.update(mata: mata_home -= 3)
          @siapa2.update(mata: mata_away += 3)
          @siapa1.update(menang: menang_home -= 1)
          @siapa2.update(menang: menang_away += 1)
          @siapa1.update(kalah: kalah_home += 1)
          @siapa2.update(kalah: kalah_away -= 1)
        elsif staff_match_report_params[:score_home_team].to_i == staff_match_report_params[:score_away_team].to_i
          @siapa1.update(mata: mata_home -= 2)
          @siapa2.update(mata: mata_away += 1)
          @siapa1.update(menang: menang_home -= 1)
          @siapa2.update(kalah: kalah_away -= 1)
          @siapa1.update(seri: seri_home += 1)
          @siapa2.update(seri: seri_away += 1)
        end
      elsif @staff_match_report.score_home_team_was < @staff_match_report.score_away_team_was
        if staff_match_report_params[:score_home_team].to_i > staff_match_report_params[:score_away_team].to_i
          @siapa1.update(mata: mata_home += 3)
          @siapa2.update(mata: mata_away -= 3)
          @siapa1.update(menang: menang_home += 1)
          @siapa2.update(menang: menang_away -= 1)
          @siapa1.update(kalah: kalah_home -= 1)
          @siapa2.update(kalah: kalah_away += 1)
        elsif staff_match_report_params[:score_home_team].to_i == staff_match_report_params[:score_away_team].to_i
          @siapa1.update(mata: mata_home += 1)
          @siapa2.update(mata: mata_away -= 2)
          @siapa1.update(kalah: kalah_home -= 1)
          @siapa2.update(menang: menang_away -= 1)
          @siapa1.update(seri: seri_home += 1)
          @siapa2.update(seri: seri_away += 1)
        end
      elsif @staff_match_report.score_home_team_was == @staff_match_report.score_away_team_was
        if staff_match_report_params[:score_home_team].to_i < staff_match_report_params[:score_away_team].to_i
          @siapa1.update(mata: mata_home -= 1)
          @siapa2.update(mata: mata_away += 2)
          @siapa1.update(seri: seri_home -= 1)
          @siapa2.update(seri: seri_away -= 1)
          @siapa1.update(kalah: kalah_home += 1)
          @siapa2.update(menang: menang_away += 1)
        elsif staff_match_report_params[:score_home_team].to_i > staff_match_report_params[:score_away_team].to_i
          @siapa1.update(mata: mata_home += 2)
          @siapa2.update(mata: mata_away -= 1)
          @siapa1.update(seri: seri_home -= 1)
          @siapa2.update(seri: seri_away -= 1)
          @siapa1.update(menang: menang_home += 1)
          @siapa2.update(kalah: kalah_away += 1)
        end
      end

      #############################
      if @staff_match_report.update_attributes staff_match_report_params
        redirect_to staff_zone_group_team_schedule_match_report_path(id:@staff_match_report), notice: "Keputusan perlawanan berjaya dikemaskini."
      else
        render 'edit'
      end
  end

  def destroy
    @group = Staff::Group.find params[:group_id]
    @staff_team_schedule = Staff::TeamSchedule.find params[:team_schedule_id]
    @staff_match_report = Staff::MatchReport.find params[:id]
    @siapa1 = Staff::GroupTeam.find_by_team_id (@staff_team_schedule.home_team_id)

app/controllers/staff/team_officials_controller.rb
class Staff::TeamOfficialsController < StaffController

  def index
    @team = Team.find(params[:team_id])
    @team_officials = TeamOfficial.where(team_id: params[:team_id])
    # generate PDF
    respond_to do |format|
      format.html
      format.pdf do
        pdf = LoTeamOfficialPdf.new(@team_officials, @team, view_context)
        send_data pdf.render, filename:
        "TeamOfficials-#{@team.team_name}.pdf",
        type: "application/pdf",
        disposition: "inline"
      end
    end
  end

  def show
    @team_official = TeamOfficial.find(params[:id])
    # generate PDF
    respond_to do |format|
      format.html
      format.pdf do
        pdf = TagPegawaiPdf.new(@team_official, view_context)
        send_data pdf.render, filename:
        "TeamOfficials-#{@team_official.name}.pdf",
        type: "application/pdf",
        disposition: "inline"
      end
    end
  end
end

app/controllers/staff/team_players_controller.rb
class Staff::TeamPlayersController < StaffController
  def index
    @team = Team.find(params[:team_id])
    @team_players = TeamPlayer.where(team_id: params[:team_id])
    # generate PDF
    respond_to do |format|
      format.html
      format.pdf do
        pdf = LoTeamPlayerPdf.new(@team_players, @team, view_context)
        send_data pdf.render, filename:
        "TeamPlayers-#{@team.team_name}.pdf",
        type: "application/pdf",
        disposition: "inline"
      end
    end
  end

  def show
    @team_player = TeamPlayer.find(params[:id])
    # generate PDF
    respond_to do |format|
      format.html
      format.pdf do
        pdf = TagPemainPdf.new(@team_player, view_context)
        send_data pdf.render, filename:
        "TeamPlayers-#{@team_player.player_name}.pdf",
        type: "application/pdf",
        disposition: "inline"
      end
    end
  end
end

app/controllers/staff/teams_controller.rb
class Staff::TeamsController < StaffController

  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
  end
end

app/controllers/staff/zones_controller.rb
class Staff::ZonesController < StaffController
  def index
    @staff_zones = Staff::Zone.all
  end
end

app/controllers/staff_controller.rb
class StaffController < ApplicationController
  layout 'dashboard'
  before_filter :require_staff
end

app/helpers/staff/group_teams_helper.rb
module Staff::GroupTeamsHelper
end

app/helpers/staff/groups_helper.rb
module Staff::GroupsHelper
end

app/helpers/staff/match_reports_helper.rb
module Staff::MatchReportsHelper
end

app/helpers/staff/team_officials_helper.rb
module Staff::TeamOfficialsHelper
end

app/views/staff/team_schedules/edit.html.erb
<section role="main" class="content-body">
  <header class="page-header">
    <h2>Kemaskini Jadual Perlawanan</h2>
    <div class="right-wrapper pull-right">
      <ol class="breadcrumbs">
        <li>
          <%= link_to root_path do %>
            <i class="fa fa-home"></i>
          <% end %>
        </li>
        <li>
          <span>Kemaskini Jadual Perlawanan</span>
        </li>
      </ol>
      <a class="sidebar-right-toggle" data-open="sidebar-right">
        <i class="fa fa-chevron-left"></i>
      </a>
    </div>
  </header>
  <div class="row">
    <div class="col-md-12">
      <section class="panel">
        <header class="panel-heading">
          <h2 class="panel-title">Kemaskini Jadual Perlawanan</h2>
        </header>
        <div class="panel-body">
          <!-- Main Content Start -->
          <%= form_for @staff_team_schedule, url: staff_zone_group_team_schedule_path, multipart: true, html: { class: "form-horizontal form-bordered", method: :patch } do |f| %>
            <%= render partial: 'form', locals: {f: f, post: @staff_team_schedule} %>
          <% end %>
          <!-- Main Content End -->
        </div>
      </section>
    </div>
  </div>
</section>

app/views/staff/team_schedules/index.html.erb
<section role="main" class="content-body">
  <header class="page-header">
    <h2>Jadual Perlawanan</h2>
    <div class="right-wrapper pull-right">
      <ol class="breadcrumbs">
        <li>
          <%= link_to root_path do %>
            <i class="fa fa-home"></i>
          <% end %>
        </li>
        <li>
          <span>Jadual Perlawanan Kumpulan <%= @group.name %></span>
        </li>
      </ol>
      <a class="sidebar-right-toggle" data-open="sidebar-right">
        <i class="fa fa-chevron-left"></i>
      </a>
    </div>
  </header>
  <div class="row">
    <div class="col-md-12">
      <section class="panel">
        <header class="panel-heading">
          <h2 class="panel-title">Jadual Perlawanan bagi Kumpulan <%= @group.name %></h2>
        </header>
        <div class="panel-body">
          <!-- Main Content Start -->
          <table class="table table-bordered table-striped mb-none" id="datatable-lbr">
            <thead>
              <tr>
                <th class="col-md-1">Bil</th>
                <th class="col-md-1">Bil. Perl</th>
                <th>Nama Pasukan (Home)</th>
                <th>Nama Pasukan (Away)</th>
                <th class="col-md-1">Tarikh Perl</th>
                <th class="col-md-1">Masa Perl</th>
                <th class="col-md-1">Status</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @staff_team_schedules.each_with_index do |team_schedule,index| %>
              <% @st = Staff::MatchReport.find_by_staff_team_schedule_id team_schedule %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= team_schedule.bil_per.upcase %></td>
                <td class="<%= 'winner' if @st.present? && @st.score_home_team > @st.score_away_team %><%= 'draw' if @st.present? && @st.score_home_team == @st.score_away_team %>">[ <%= @st.score_home_team if @st.present? %> ] <%= team_schedule.home_team.team_name %></td>
                <td class="<%= 'winner' if @st.present? && @st.score_away_team > @st.score_home_team %><%= 'draw' if @st.present? && @st.score_away_team == @st.score_home_team %>">[ <%= @st.score_away_team if @st.present? %> ] <%= team_schedule.away_team.team_name %></td>
                <td><%= team_schedule.tarikh_perl.strftime("%d/%m/%Y") %></td>
                <td><%= team_schedule.masa_perl.strftime("%I:%M %p") %></td>
                <% if @st.present? %>
                <td><span class="label label-primary">bermain</span></td>
                <% else %>
                <td><span class="label label-warning">menunggu</span></td>
                <% end %>
                <td><%= link_to "detail", staff_zone_group_team_schedule_path(id:team_schedule) %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <!-- Main Content End -->
        </div>
        <div class="panel-footer">
          <%= link_to "Masuk Jadual", new_staff_zone_group_team_schedule_path, class: "btn btn-primary" %>
          <%= link_to "Kembali Ke Senarai Pasukan", staff_zone_group_group_teams_path, class: "btn btn-default" %>
        </div>
      </section>
    </div>
  </div>
</section>

app/views/staff/team_schedules/show.html.erb
<section role="main" class="content-body">
  <header class="page-header">
    <h2>Detail Perlawanan</h2>
    <div class="right-wrapper pull-right">
      <ol class="breadcrumbs">
        <li>
          <%= link_to root_path do %>
            <i class="fa fa-home"></i>
          <% end %>
        </li>
        <li>
          <span>Detail Perlawanan</span>
        </li>
      </ol>
      <a class="sidebar-right-toggle" data-open="sidebar-right">
        <i class="fa fa-chevron-left"></i>
      </a>
    </div>
  </header>
  <div class="row">
    <div class="col-md-12">
      <section class="panel">
        <header class="panel-heading bg-primary">
          <div class="widget-profile-info">
            <div class="row">
              <div class="col-md-5">
                <div class="profile-picture">
                  <% if @staff_team_schedule.home_team.try(:team_logo?) %>
                    <%= image_tag(@staff_team_schedule.home_team.team_logo_url(:low_res)) %>
                  <% else %>
                    <%= image_tag "default-team-avatar.jpg" %>
                  <% end %>
                </div>
                <div class="profile-info" style="vertical-align:middle;">
                  <h2 class="name text-weight-semibold"><%= @staff_team_schedule.home_team.team_name.upcase %></h2>
                </div>
              </div>
              <div class="col-md-2">
                <div class="profile-info" style="vertical-align:middle;">
                  <h1 class="name text-weight-semibold" style="margin-top:32px;">vs</h1>
                </div>
              </div>
              <div class="col-md-5">
                <div class="profile-picture">
                  <% if @staff_team_schedule.away_team.try(:team_logo?) %>
                    <%= image_tag(@staff_team_schedule.away_team.team_logo_url(:low_res)) %>
                  <% else %>
                    <%= image_tag "default-team-avatar.jpg" %>
                  <% end %>
                </div>
                <div class="profile-info" style="vertical-align:middle;">
                  <h2 class="name text-weight-semibold"><%= @staff_team_schedule.away_team.team_name.upcase %></h2>
                </div>
              </div>
            </div>
          </div>
        </header>
        <div class="panel-body">
          <!-- Main Content Start -->
          <table class="table table-bordered">
            <thead>
              <tr></tr>
            </thead>
            <tbody>
              <tr>
                <td>Bilangan Perlawanan</td>
                <td><strong><%= @staff_team_schedule.bil_per %></strong></td>
              </tr>
              <tr>
                <td>PBN</td>
                <td><strong><%= @staff_team_schedule.pbn %></strong></td>
              </tr>
              <tr>
                <td>Tarikh Perlawanan</td>
                <td><strong><%= @staff_team_schedule.tarikh_perl.strftime("%d %B %Y") %></strong></td>
              </tr>
              <tr>
                <td>Masa Perlawanan</td>
                <td><strong><%= @staff_team_schedule.masa_perl.strftime("%I:%M %p") %></strong></td>
              </tr>
              <tr>
                <td>Venue</td>
                <td><strong><%= @staff_team_schedule.venue %></strong></td>
              </tr>
              <!-- <tr>
                <td>Status</td>
                <td>
                  <span class="label <%#= @staff_team_schedule.incoming? ? 'label-warning' : @staff_team_schedule.played? ? 'label-primary' : 'label-danger' %>">
                    <%#= @staff_team_schedule.status.upcase %>
                  </span>
                </td>
              </tr> -->
            </tbody>
          </table>
          <!-- Main Content End -->
        </div>
        <div class="panel-footer">
          <%#= link_to "Kemaskini", edit_team_team_player_path(@team_player), class: "btn btn-primary" %>
          <%= link_to "Muat Turun Senarai Pemilihan dalam PDF", selection_staff_zone_group_team_schedules_path(group_id:@staff_team_schedule, :format => "pdf"), :class => "btn btn-success", :target => "_blank" %>
          <%= link_to "Kembali", staff_zone_group_team_schedules_path(group_id:@group), class: "btn btn-default" %>
          <% if @staff_match_report.exists? %>
            <%= link_to "Keputusan Perlawanan", staff_zone_group_team_schedule_match_report_path(team_schedule_id: @staff_team_schedule, id: @staff_match_report.ids), :class => "btn btn-primary" %>
          <% else %>
            <%= link_to "Masuk Keputusan Perlawanan", new_staff_zone_group_team_schedule_match_report_path(team_schedule_id: @staff_team_schedule), :class => "btn btn-primary" %>
          <% end %>
          <%= link_to "Kemaskini Jadual", edit_staff_zone_group_team_schedule_path(id:@staff_team_schedule), class: "btn btn-warning pull-right" %>
        </div>
      </section>
    </div>
  </div>
</section>