config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    omniauth: 'users/omniauth',
    unlocks: 'users/unlocks'
  }
  devise_scope :user do
    delete 'sign_out', :to => 'users/sessions#destroy'
    get '/login' => 'users/sessions#new'
    get '/register' => 'users/registrations#new'
    get '/settings' => 'users/registrations#edit'
    root 'users/sessions#new'
  end

  namespace :admin, path: '/master' do
    resources :teams do
      resources :team_officials
      resources :team_players
    end

    resources :pages, only: :index

    # sort by state
    get 't/:sort' => 'pages#state', as: 'state_index'
    get 't/:sort/team_players' => 'pages#team_player', as: 'team_player_state_index'
    get 't/:sort/team_officials' => 'pages#team_official', as: 'team_official_state_index'
  end

  namespace :staff, path: '/submaster' do
    resources :teams, only: [:index, :show] do
      resources :team_officials, only: [:index, :show]
      resources :team_players, only: [:index, :show]
    end
    resources :zones do
      resources :groups do
        resources :group_teams
        resources :team_schedules do
          collection do
            get :selection
          end
          resources :match_reports, except: :index
        end
      end
    end
  end

  namespace :lo, path: '/sub2master' do
    resources :teams, only: [:index, :show] do
      resources :team_officials, only: [:index, :show]
      resources :team_players, only: [:index, :show]
    end
  end

  get "/dashboard" => 'dashboards#index'
  resource :team, only: [:new, :create, :show] do
    resources :team_officials, only: [:index, :new, :create, :show, :edit, :update]
    # choose either one
    # activate new registration player
    # resources :team_players, only: [:index, :new, :create, :show, :edit, :update] do
    # de-activate new and edit player
    # resources :team_players, only: [:index, :show], except: [:new, :create, :edit, :update]
    # activate edit player only
    resources :team_players, only: [:index, :show, :edit, :update, :new, :create] do
      member do
        patch :mark_reject
      end
    end
    get 'cs/change_players' => 'team_players#change_players'
  end
  resource :team_config, only: [:show, :new, :create]
  resource :state_config, only: [:show, :new, :create]
  resources :state_managers
  resources :team_managers, except: [:show]
  resource :profile, only: [:edit, :update]
  resource :system_preference, only: [:edit, :update]

  get "/p/table_standing" => 'pages#table_standing'
  get "/p/match_schedule" => 'pages#match_schedule'
  get "/p/search" => 'pages#search', as: :search
end

app/controllers/admin/team_players_controller.rb
class Admin::TeamPlayersController < AdminController

  def index
    @team = Team.find(params[:team_id])
    @team_players = TeamPlayer.where(team_id: params[:team_id])
    # generate PDF
    respond_to do |format|
      format.html
      format.pdf do
        pdf = LoTeamPlayerPdf.new(@team_players, @team, view_context)
        send_data pdf.render, filename:
        "TeamPlayers-#{@team.team_name}.pdf",
        type: "application/pdf",
        disposition: "inline"
      end
    end
  end

  def new
    @team_player ||= TeamPlayer.new
    render
  end

  def create
    @team = Team.find params[:team_id]
    @team_player = TeamPlayer.new team_player_params
    if @team_player.save
      @team_player.update_attribute(:team_id, @team.id)
      redirect_to admin_team_team_players_path, notice: "Tahniah! Pemain berjaya diwujudkan."
    else
      render 'new'
    end
  end

  def show
    @team_player = TeamPlayer.find(params[:id])
    # generate PDF
    respond_to do |format|
      format.html
      format.pdf do
        pdf = TagPemainPdf.new(@team_player, view_context)
        send_data pdf.render, filename:
        "TeamPlayers-#{@team_player.player_name}.pdf",
        type: "application/pdf",
        disposition: "inline"
      end
    end
  end

  def edit
    @team_player = TeamPlayer.find(params[:id])
    if @team_player
      render
    else
      redirect_to admin_team_team_player_path(@team_player), notice: "Maaf! Pasukan tidak dijumpai!"
    end
  end

  def update
    @team_player = TeamPlayer.find(params[:id])
    if @team_player.update_attributes team_player_params
      redirect_to admin_team_team_player_path(id:@team_player), notice: "Data Pemain Pasukan berjaya dikemaskini."
    else
      render 'edit'
    end
  end

  def destroy
    @team_player = TeamPlayer.find(params[:id])
    if @team_player.destroy
      redirect_to admin_team_team_players_path, notice: 'Data pemain berjaya dihapuskan!'
    else
      render 'index'
    end
  end

  private

    def team_player_params
      params.require(:team_player).permit(:player_name, :player_picture, :player_picture_cache, :ic_number, :ic_picture, :ic_picture_cache, :dob, :position, :jersey_no, :team_id)
    end
end

app/controllers/lo/team_players_controller.rb
class Lo::TeamPlayersController < LoController
  def index
    @team = Team.find params[:team_id]
    if current_user.state_id == @team.state_id
      @team_players = TeamPlayer.where(team_id: params[:team_id])
      # generate PDF
      respond_to do |format|
        format.html
        format.pdf do
          pdf = LoTeamPlayerPdf.new(@team_players, @team, view_context)
          send_data pdf.render, filename:
          "TeamPlayers-#{@team.team_name}.pdf",
          type: "application/pdf",
          disposition: "inline"
        end
      end
    else
      redirect_to lo_teams_path, notice: "You have no authorization to this team!"
    end
  end

  def show
    @team_player = TeamPlayer.find(params[:id])
    # generate PDF
    respond_to do |format|
      format.html
      format.pdf do
        pdf = TagPemainPdf.new(@team_player, view_context)
        send_data pdf.render, filename:
        "TeamPlayers-#{@team_player.player_name}.pdf",
        type: "application/pdf",
        disposition: "inline"
      end
    end
  end
end

app/controllers/staff/group_teams_controller.rb
class Staff::GroupTeamsController < StaffController
  def index
    @group = Staff::Group.find params[:group_id]
    @staff_group_teams = Staff::GroupTeam.where(staff_group_id: @group)
  end

  def new
    @group = Staff::Group.find params[:group_id]
    @staff_group_team ||= Staff::GroupTeam.new
    render
  end

  def create
    @group = Staff::Group.find params[:group_id]
    @staff_group_team = Staff::GroupTeam.new team_staff_group_params
    if @staff_group_team.save
      @staff_group_team.update_attribute(:staff_group_id, @group.id)
      redirect_to staff_zone_group_group_teams_path, notice: "Kumpulan berjaya diwujudkan."
    else
      render 'new'
    end
  end

  def edit
    #code
  end

  def update
    #code
  end

  private

    def team_staff_group_params
      params.require(:staff_group_team).permit(:team_id, :staff_group_id)
    end
end

app/controllers/staff/groups_controller.rb
class Staff::GroupsController < StaffController
  def index
    @zone = Staff::Zone.find params[:zone_id]
    @staff_groups = Staff::Group.where(staff_zone_id: @zone)
  end

  def new
    @zone = Staff::Zone.find params[:zone_id]
    @staff_group ||= Staff::Group.new
    render
  end

  def create
    @zone = Staff::Zone.find params[:zone_id]
    @staff_group = Staff::Group.new team_staff_group_params
    if @staff_group.save
      @staff_group.update_attribute(:staff_zone_id, @zone.id)
      redirect_to staff_zone_groups_path, notice: "Kumpulan berjaya diwujudkan."
    else
      render 'new'
    end
  end

  private

    def team_staff_group_params
      params.require(:staff_group).permit(:name, :staff_zone_id)
    end
end

app/controllers/staff/match_reports_controller.rb
class Staff::MatchReportsController < StaffController
  def show
    @group = Staff::Group.find params[:group_id]
    @staff_team_schedule = Staff::TeamSchedule.find params[:team_schedule_id]
    @staff_match_report = Staff::MatchReport.find params[:id]
  end

  def new
    @staff_team_schedule = Staff::TeamSchedule.find params[:team_schedule_id]

    @home_team_players = TeamPlayer.where(team_id: @staff_team_schedule.home_team_id)
    @away_team_players = TeamPlayer.where(team_id: @staff_team_schedule.away_team_id)
    @players = @home_team_players + @away_team_players

    @staff_match_report = Staff::MatchReport.new
    @staff_match_report.staff_game_statistics.build
    render
  end

  def create
    @staff_team_schedule = Staff::TeamSchedule.find params[:team_schedule_id]
    @staff_match_report = Staff::MatchReport.new staff_match_report_params
    if @staff_match_report.save
      @staff_match_report.update_attributes(staff_team_schedule_id: @staff_team_schedule.id)

      @siapa1 = Staff::GroupTeam.find_by_team_id (@staff_team_schedule.home_team_id)
      @siapa2 = Staff::GroupTeam.find_by_team_id (@staff_team_schedule.away_team_id)

        current_home_gm = @siapa1.gol_masuk
        current_home_gb = @siapa1.gol_bolos
        current_away_gm = @siapa2.gol_masuk
        current_away_gb = @siapa2.gol_bolos
        perlawanan_home = @siapa1.perlawanan
        perlawanan_away = @siapa2.perlawanan
        menang_home = @siapa1.menang
        menang_away = @siapa2.menang
        kalah_home = @siapa1.kalah
        kalah_away = @siapa2.kalah
        seri_home = @siapa1.seri
        seri_away = @siapa2.seri
        mata_home = @siapa1.mata
        mata_away = @siapa2.mata

        rm = @staff_match_report
        sm = rm.staff_team_schedule.home_team_id = @siapa1.team_id
        tm = Staff::MatchReport.joins(:staff_team_schedule).where("home_team_id = ?", sm)
        gm = tm.last.score_home_team

        rb = @staff_match_report
        sb = rb.staff_team_schedule.home_team_id = @siapa1.team_id
        tb = Staff::MatchReport.joins(:staff_team_schedule).where("home_team_id = ?", sb)
        gb = tb.last.score_away_team

        @siapa1.update(gol_masuk: current_home_gm += gm)
        @siapa1.update(gol_bolos: current_home_gb += gb)
        @siapa2.update(gol_masuk: current_away_gm += gb)
        @siapa2.update(gol_bolos: current_away_gb += gm)
        @siapa1.update(perlawanan: perlawanan_home += 1)
        @siapa2.update(perlawanan: perlawanan_away += 1)

        if gm > gb
          @siapa1.update(menang: menang_home += 1)
          @siapa1.update(mata: mata_home += 3)
          @siapa2.update(kalah: kalah_away += 1)
          @siapa2.update(mata: mata_away += 0)
        elsif gm < gb
          @siapa1.update(kalah: kalah_home += 1)
          @siapa1.update(mata: mata_home += 0)
          @siapa2.update(menang: menang_away += 1)
          @siapa2.update(mata: mata_away += 3)
        elsif gm == gb
          @siapa1.update(seri: seri_home += 1)
          @siapa2.update(seri: seri_away += 1)
          @siapa1.update(mata: mata_home += 1)
          @siapa2.update(mata: mata_away += 1)
        end

      redirect_to staff_zone_group_team_schedule_match_report_path(id:@staff_match_report), notice: "Disimpan."
    else
      render 'new'
    end
  end

  def edit
    @group = Staff::Group.find params[:group_id]
    @staff_team_schedule = Staff::TeamSchedule.find params[:team_schedule_id]
    @staff_match_report = Staff::MatchReport.find params[:id]
    if @staff_match_report
      render
    else
      redirect_to staff_zone_group_team_schedule_match_report_path(id:@staff_match_report), notice: "Maaf! Keputusan perlawanan tidak dijumpai!"
    end
  end

  def update
    @group = Staff::Group.find params[:group_id]
    @staff_team_schedule = Staff::TeamSchedule.find params[:team_schedule_id]
    @staff_match_report = Staff::MatchReport.find params[:id]
    ###############################################

    @siapa1 = Staff::GroupTeam.find_by_team_id (@staff_team_schedule.home_team_id)
    @siapa2 = Staff::GroupTeam.find_by_team_id (@staff_team_schedule.away_team_id)

      current_home_gm = @siapa1.gol_masuk
      current_home_gb = @siapa1.gol_bolos
      current_away_gm = @siapa2.gol_masuk
      current_away_gb = @siapa2.gol_bolos
      menang_home = @siapa1.menang
      menang_away = @siapa2.menang
      kalah_home = @siapa1.kalah
      kalah_away = @siapa2.kalah
      seri_home = @siapa1.seri
      seri_away = @siapa2.seri
      mata_home = @siapa1.mata
      mata_away = @siapa2.mata

      rm = @staff_match_report
      sm = rm.staff_team_schedule.home_team_id = @siapa1.team_id
      tm = Staff::MatchReport.joins(:staff_team_schedule).where("home_team_id = ?", sm)
      gm = tm.last.score_home_team

      rb = @staff_match_report
      sb = rb.staff_team_schedule.home_team_id = @siapa1.team_id
      tb = Staff::MatchReport.joins(:staff_team_schedule).where("home_team_id = ?", sb)
      gb = tb.last.score_away_team

      # keputusan asal home = 2
      # edit keputusan home = 3
      # current_home_gm = 3
      # current_home_gb = 2

      # keputusan asal away = 3
      # edit keputusan away = 4
      # current_away_gm = 3
      # current_away_gb = 2

      # 3 > 2 home
      if staff_match_report_params[:score_home_team].to_i > @staff_match_report.score_home_team_was
        scgm = staff_match_report_params[:score_home_team].to_i - @staff_match_report.score_home_team_was

        @siapa1.update(gol_masuk: current_home_gm += scgm)
        @siapa2.update(gol_bolos: current_away_gb += scgm)
      end
      # 3 < 2 home
      if staff_match_report_params[:score_home_team].to_i < @staff_match_report.score_home_team_was
        scgm = @staff_match_report.score_home_team_was - staff_match_report_params[:score_home_team].to_i

        @siapa1.update(gol_masuk: current_home_gm -= scgm)
        @siapa2.update(gol_bolos: current_away_gb -= scgm)
      end

      if staff_match_report_params[:score_away_team].to_i > @staff_match_report.score_away_team_was
        scgm = staff_match_report_params[:score_away_team].to_i - @staff_match_report.score_away_team_was

        @siapa2.update(gol_masuk: current_away_gm += scgm)
        @siapa1.update(gol_bolos: current_home_gb += scgm)
      end
      # 3 < 2 home
      if staff_match_report_params[:score_away_team].to_i < @staff_match_report.score_away_team_was
        scgm = @staff_match_report.score_away_team_was - staff_match_report_params[:score_away_team].to_i

        @siapa2.update(gol_masuk: current_away_gm -= scgm)
        @siapa1.update(gol_bolos: current_home_gb -= scgm)
      end
      # reset
      if @staff_match_report.score_home_team_was > @staff_match_report.score_away_team_was
        if staff_match_report_params[:score_home_team].to_i < staff_match_report_params[:score_away_team].to_i
          @siapa1.update(mata: mata_home -= 3)
          @siapa2.update(mata: mata_away += 3)
          @siapa1.update(menang: menang_home -= 1)
          @siapa2.update(menang: menang_away += 1)
          @siapa1.update(kalah: kalah_home += 1)
          @siapa2.update(kalah: kalah_away -= 1)
        elsif staff_match_report_params[:score_home_team].to_i == staff_match_report_params[:score_away_team].to_i
          @siapa1.update(mata: mata_home -= 2)
          @siapa2.update(mata: mata_away += 1)
          @siapa1.update(menang: menang_home -= 1)
          @siapa2.update(kalah: kalah_away -= 1)
          @siapa1.update(seri: seri_home += 1)
          @siapa2.update(seri: seri_away += 1)
        end
      elsif @staff_match_report.score_home_team_was < @staff_match_report.score_away_team_was
        if staff_match_report_params[:score_home_team].to_i > staff_match_report_params[:score_away_team].to_i
          @siapa1.update(mata: mata_home += 3)
          @siapa2.update(mata: mata_away -= 3)
          @siapa1.update(menang: menang_home += 1)
          @siapa2.update(menang: menang_away -= 1)
          @siapa1.update(kalah: kalah_home -= 1)
          @siapa2.update(kalah: kalah_away += 1)
        elsif staff_match_report_params[:score_home_team].to_i == staff_match_report_params[:score_away_team].to_i
          @siapa1.update(mata: mata_home += 1)
          @siapa2.update(mata: mata_away -= 2)
          @siapa1.update(kalah: kalah_home -= 1)
          @siapa2.update(menang: menang_away -= 1)
          @siapa1.update(seri: seri_home += 1)
          @siapa2.update(seri: seri_away += 1)
        end
      elsif @staff_match_report.score_home_team_was == @staff_match_report.score_away_team_was
        if staff_match_report_params[:score_home_team].to_i < staff_match_report_params[:score_away_team].to_i
          @siapa1.update(mata: mata_home -= 1)
          @siapa2.update(mata: mata_away += 2)
          @siapa1.update(seri: seri_home -= 1)
          @siapa2.update(seri: seri_away -= 1)
          @siapa1.update(kalah: kalah_home += 1)
          @siapa2.update(menang: menang_away += 1)
        elsif staff_match_report_params[:score_home_team].to_i > staff_match_report_params[:score_away_team].to_i
          @siapa1.update(mata: mata_home += 2)
          @siapa2.update(mata: mata_away -= 1)
          @siapa1.update(seri: seri_home -= 1)
          @siapa2.update(seri: seri_away -= 1)
          @siapa1.update(menang: menang_home += 1)
          @siapa2.update(kalah: kalah_away += 1)
        end
      end

      #############################
      if @staff_match_report.update_attributes staff_match_report_params
        redirect_to staff_zone_group_team_schedule_match_report_path(id:@staff_match_report), notice: "Keputusan perlawanan berjaya dikemaskini."
      else
        render 'edit'
      end
  end

  def destroy
    @group = Staff::Group.find params[:group_id]
    @staff_team_schedule = Staff::TeamSchedule.find params[:team_schedule_id]
    @staff_match_report = Staff::MatchReport.find params[:id]
    @siapa1 = Staff::GroupTeam.find_by_team_id (@staff_team_schedule.home_team_id)

app/views/staff/team_players/index.html.erb
<section role="main" class="content-body">
  <header class="page-header">
    <h2>Senarai Pemain Pasukan</h2>
    <div class="right-wrapper pull-right">
      <ol class="breadcrumbs">
        <li>
          <%= link_to root_path do %>
            <i class="fa fa-home"></i>
          <% end %>
        </li>
        <li>
          <span>Senarai Pemain Pasukan</span>
        </li>
      </ol>
      <a class="sidebar-right-toggle" data-open="sidebar-right">
        <i class="fa fa-chevron-left"></i>
      </a>
    </div>
  </header>
  <div class="row">
    <div class="col-md-12">
      <section class="panel">
        <header class="panel-heading">
          <h2 class="panel-title">Senarai Pemain Pasukan <%= @team.team_name.upcase %></h2>
        </header>
        <div class="panel-body">
          <!-- Main Content Start -->
          <table class="table table-bordered table-striped mb-none" id="datatable-lbr">
            <thead>
              <tr>
                <th class="col-md-1">Bil</th>
                <th>Nama</th>
                <th class="col-md-2">Posisi</th>
                <th class="col-md-2">No Jersi</th>
                <th class="col-md-2">Umur</th>
                <th class="col-md-2"></th>
              </tr>
            </thead>
            <tbody>
              <% @team_players.each_with_index do |tp, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td>
                  <% if tp.try(:player_picture?) %>
                    <%= image_tag(tp.player_picture_url(:standar), class: 'img-circle', height: 15) %>
                  <% else %>
                    <%= image_tag "default-avatar.png", class: 'img-circle', height: 15 %>
                  <% end %>
                  <%= tp.player_name.upcase %>
                </td>
                <td><%= tp.position.upcase %></td>
                <td><%= tp.jersey_no %></td>
                <td><%= tp.age %> tahun</td>
                <td><%= link_to "Lihat Data", staff_team_team_player_path(id:tp) %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <!-- Main Content End -->
        </div>
        <div class="panel-footer">
          <%= link_to "Kembali ke Data Pasukan", staff_team_path(@team), class: "btn btn-default" %>
          <%= link_to "Muat Turun dalam PDF", staff_team_team_players_path(@team, :format => "pdf"), :class => "btn btn-primary", :target => "_blank" %>
        </div>
      </section>
    </div>
  </div>
</section>

app/views/staff/team_players/show.html.erb
<section role="main" class="content-body">
  <header class="page-header">
    <h2>Data Pemain</h2>
    <div class="right-wrapper pull-right">
      <ol class="breadcrumbs">
        <li>
          <%= link_to root_path do %>
            <i class="fa fa-home"></i>
          <% end %>
        </li>
        <li>
          <span>Data Pemain</span>
        </li>
      </ol>
      <a class="sidebar-right-toggle" data-open="sidebar-right">
        <i class="fa fa-chevron-left"></i>
      </a>
    </div>
  </header>
  <div class="row">
    <div class="col-md-12">
      <section class="panel">
        <header class="panel-heading bg-primary">
          <div class="widget-profile-info">
            <div class="profile-picture">
              <% if @team_player.try(:player_picture?) %>
                <%= image_tag(@team_player.player_picture_url(:standar)) %>
              <% else %>
                <%= image_tag "default-avatar.png" %>
              <% end %>
            </div>
            <div class="profile-info">
              <h4 class="name text-weight-semibold"><%= @team_player.player_name %></h4>
              <h5 class="role"><%= @team_player.position %></h5>
              <div class="profile-footer">
                Tarikh akhir kemaskini: <%= @team_player.updated_at.strftime("%d %B %Y") %>
              </div>
            </div>
          </div>
        </header>
        <div class="panel-body">
          <!-- Main Content Start -->
          <h4>Keterangan Pemain</h4>
          <table class="table table-bordered">
            <thead>
              <tr></tr>
            </thead>
            <tbody>
              <tr>
                <td>Nama Penuh</td>
                <td><strong><%= @team_player.player_name %></strong></td>
              </tr>
              <tr>
                <td>ID Pemain</td>
                <td><strong><%= @team_player.ref_id %></strong></td>
              </tr>
              <tr>
                <td>No. Kad Pengenalan</td>
                <td><strong><%= @team_player.ic_number %></strong> <% if @team_player.try(:ic_picture?) %><%= link_to "(lihat gambar)", @team_player.ic_picture_url, target: "_blank" %><% end %></td>
              </tr>
              <tr>
                <td>Tarikh Lahir</td>
                <td><strong><%= @team_player.dob.strftime("%d %B %Y") %> (<%= @team_player.age %> tahun)</strong></td>
              </tr>
              <tr>
                <td>Posisi Pemain</td>
                <td><strong><%= @team_player.position %></strong></td>
              </tr>
              <tr>
                <td>No Jersi</td>
                <td><strong><%= @team_player.jersey_no %></strong></td>
              </tr>
              <tr>
                <td>Status</td>
                <td>
                  <span class="label <%= @team_player.in_review? ? 'label-warning' : @team_player.registered? ? 'label-primary' : 'label-danger' %>">
                    <%= @team_player.status.upcase %>
                  </span>
                </td>
              </tr>
              <tr>
                <td>Pasukan</td>
                <td><strong><%= @team_player.team.team_name.upcase %></strong></td>
              </tr>
            </tbody>
          </table>
          <!-- Main Content End -->
        </div>
        <div class="panel-footer">
          <%= link_to "Kembali ke Senarai Pemain", staff_team_team_players_path, class: "btn btn-default" %>
          <%= link_to "Muat Turun TAG Pemain", lo_team_team_player_path(id:@team_player, :format => "pdf"), :class => "btn btn-success", :target => "_blank" %>
        </div>
      </section>
    </div>
  </div>
</section>